import { afterEach, describe, expect, it, vi } from 'vitest'
import { DiskBatch } from '../src/disk-batch.js'

afterEach(() => vi.useRealTimers())
describe('disk publish scheduling', () => {
  it('exposes pending and in-flight paths for synchronous scope transitions', async () => {
    vi.useFakeTimers()
    let finish!: () => void
    const batch = new DiskBatch(() => new Promise<void>(resolve => { finish = resolve }))
    batch.add('a', false)
    expect(batch.knownPaths()).toEqual(['a'])
    await vi.advanceTimersByTimeAsync(300)
    expect(batch.knownPaths()).toEqual(['a'])
    finish()
    for (let i = 0; i < 4; i++) await Promise.resolve()
    expect(batch.knownPaths()).toEqual([])
    batch.stop()
  })
  it('keeps overlapping runs counted until both finish, even after stop', async () => {
    vi.useFakeTimers()
    const finishes: Array<() => void> = []
    const batch = new DiskBatch(() => new Promise<void>(resolve => { finishes.push(resolve) }))
    batch.add('a', false)
    await vi.advanceTimersByTimeAsync(300)
    batch.add('a', false)
    await vi.advanceTimersByTimeAsync(300)
    expect(batch.knownPaths()).toEqual(['a'])
    finishes[0]()
    await Promise.resolve()
    expect(batch.knownPaths()).toEqual(['a'])
    batch.stop()
    finishes[1]()
    for (let i = 0; i < 4; i++) await Promise.resolve()
    expect(batch.knownPaths()).toEqual([])
  })
  it.each(['throw', 'reject'])('cleans up a synchronous %s and rearms pending work', async mode => {
    vi.useFakeTimers()
    const errors: unknown[] = []
    const run = vi.fn((paths: Map<string, boolean>) => {
      if (paths.has('a')) {
        batch.add('b', false)
        if (mode === 'throw') throw new Error('git failed')
        return Promise.reject(new Error('git failed'))
      }
    })
    const batch = new DiskBatch(run, 300, Date.now, 30_000, error => errors.push(error))
    batch.add('a', false)
    await vi.advanceTimersByTimeAsync(600)
    expect(run).toHaveBeenCalledTimes(2)
    expect(errors).toHaveLength(1)
    expect(batch.knownPaths()).toEqual([])
    batch.stop()
  })
  it('batches at the trailing edge and preserves new-file classification', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    batch.add('a', true)
    await vi.advanceTimersByTimeAsync(200)
    batch.add('a', false); batch.add('b', false)
    await vi.advanceTimersByTimeAsync(299)
    expect(run).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect([...run.mock.calls[0][0]]).toEqual([['a', true], ['b', false]])
    batch.stop()
  })
  it('settles bursts of more than twenty distinct paths for two seconds', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 21; i++) batch.add(String(i), true)
    await vi.advanceTimersByTimeAsync(1999)
    expect(run).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(run.mock.calls[0][0].size).toBe(21)
    batch.stop()
  })
  it('rate-limits hot files without delaying cold files and retains the trailing update', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 6; i++) batch.published('hot')
    expect(batch.deferHot('hot')).toBe(true)
    expect(batch.deferHot('cold')).toBe(false)
    batch.add('hot', false); batch.add('cold', true)
    await vi.advanceTimersByTimeAsync(300)
    expect([...run.mock.calls[0][0].keys()]).toEqual(['cold'])
    await vi.advanceTimersByTimeAsync(10_000)
    batch.add('hot', false)
    await vi.advanceTimersByTimeAsync(19_699)
    expect(run).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(1)
    expect([...run.mock.calls[1][0].keys()]).toEqual(['hot'])
    batch.published('hot'); batch.add('hot', false)
    batch.stop()
    await vi.advanceTimersByTimeAsync(30_000)
    expect(run).toHaveBeenCalledTimes(2)
  })
  it('counts publications only within the two-minute window', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 5; i++) batch.published('a')
    await vi.advanceTimersByTimeAsync(120_000)
    batch.published('a'); batch.add('a', false)
    await vi.advanceTimersByTimeAsync(300)
    expect(run).toHaveBeenCalledTimes(1)
    batch.stop()
  })
})
