import { afterEach, describe, expect, it, vi } from 'vitest'
import { DiskBatch } from '../src/disk-batch.js'

afterEach(() => vi.useRealTimers())
describe('disk publish scheduling', () => {
  it('batches at the trailing edge and preserves new-file classification', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    batch.add('a', true)
    await vi.advanceTimersByTimeAsync(200)
    batch.add('a', false); batch.add('b', false)
    await vi.advanceTimersByTimeAsync(299)
    expect(run).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect([...run.mock.calls[0][0]]).toEqual([['a', true], ['b', false]])
    batch.stop()
  })
  it('settles bursts of more than twenty distinct paths for two seconds', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 21; i++) batch.add(String(i), true)
    await vi.advanceTimersByTimeAsync(1999)
    expect(run).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(run.mock.calls[0][0].size).toBe(21)
    batch.stop()
  })
  it('rate-limits hot files without delaying cold files and retains the trailing update', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 6; i++) batch.published('hot')
    expect(batch.deferHot('hot')).toBe(true)
    expect(batch.deferHot('cold')).toBe(false)
    batch.add('hot', false); batch.add('cold', true)
    await vi.advanceTimersByTimeAsync(300)
    expect([...run.mock.calls[0][0].keys()]).toEqual(['cold'])
    await vi.advanceTimersByTimeAsync(10_000)
    batch.add('hot', false)
    await vi.advanceTimersByTimeAsync(19_699)
    expect(run).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(1)
    expect([...run.mock.calls[1][0].keys()]).toEqual(['hot'])
    batch.published('hot'); batch.add('hot', false)
    batch.stop()
    await vi.advanceTimersByTimeAsync(30_000)
    expect(run).toHaveBeenCalledTimes(2)
  })
  it('counts publications only within the two-minute window', async () => {
    vi.useFakeTimers()
    const run = vi.fn(), batch = new DiskBatch(run)
    for (let i = 0; i < 5; i++) batch.published('a')
    await vi.advanceTimersByTimeAsync(120_000)
    batch.published('a'); batch.add('a', false)
    await vi.advanceTimersByTimeAsync(300)
    expect(run).toHaveBeenCalledTimes(1)
    batch.stop()
  })
})
