/** Ignored directories whose contents can be regenerated by a build or test run. */
export const REGENERABLE_BUILD_DIRS = [
  'dist', 'build', 'out', '.astro', '.next', '.nuxt', '.svelte-kit',
  '.turbo', '.cache', 'coverage', 'test-results', 'playwright-report',
  'node_modules', 'vendor', '__pycache__', '.pytest_cache', '.mypy_cache',
  '.ruff_cache', '.tox', '.gradle', 'target',
] as const
// A .venv/venv name alone is not enough: worker cleanup separately recognizes
// generated environments by their metadata and layout, preserving arbitrary state.

const buildDirs = new Set<string>(REGENERABLE_BUILD_DIRS)

/** Accepts a repo-relative path from Git, including directory entries ending in `/`. */
export function isRegenerableBuildPath(rel: string): boolean {
  return rel.endsWith('.tsbuildinfo') || rel.split('/').some(part => buildDirs.has(part))
}
