/** Ignored directories whose contents can be regenerated by a build or test run. */
export const REGENERABLE_BUILD_DIRS = [
  'dist', 'build', 'out', '.astro', '.next', '.nuxt', '.svelte-kit',
  '.turbo', '.cache', 'coverage', 'test-results', 'playwright-report',
  'node_modules', '__pycache__', '.pytest_cache', 'target',
] as const

const buildDirs = new Set<string>(REGENERABLE_BUILD_DIRS)

/** Accepts a repo-relative path from Git, including directory entries ending in `/`. */
export function isRegenerableBuildPath(rel: string): boolean {
  return rel.endsWith('.tsbuildinfo') || rel.split('/').some(part => buildDirs.has(part))
}
